# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            AlgoPlay
tagline:          'Technology, Thoughts, and Theories'
description:      ''
url:              http://algoplay.com
baseurl:          /

author:
  name:           'Joseph Gardner'
  email:          joe@algoplay.com
  twitter:        https://twitter.com/algoplay
  linkedin:       https://www.linkedin.com/in/josephpgardner
  github:         https://github.com/josephgardner

gems:             [jekyll-paginate]
paginate:         5
paginate_path:    "page:num"

# Custom vars
version:          2.1.0
